Added test 35.

diff --git a/bin/connect_device b/bin/connect_device
--- a/bin/connect_device
+++ b/bin/connect_device
@@ -16,9 +16,20 @@ fwdPorts=$(netstat -an | grep "LISTEN " | grep 2828)
 # Function to display currentl devices ...
 #
 showDevices(){
-	echo "$X The following devices are currently connected:"
-	echo "$X"
-	$cmd_adb devices | grep -iv "List of devices attached" | awk 'X=ENVIRON["X"]{print X "          " $1}'
+	devices=$($cmd_adb devices 2>/dev/null | grep -iv "List of devices attached")
+	if [ ! "$devices" ]
+	then
+		echo "$X "
+		echo "$X *** ERROR: No devices are listed as connected to this machine! ***"
+		echo "$X "
+		echo ""
+		exit 1
+	else
+		echo "$X The following devices are currently connected:"
+		echo "$X"
+ 		echo "$devices" | awk 'X=ENVIRON["X"]{print X "          " $1}'
+		echo "$X"
+	fi
 }
 
 if [ "$fwdPorts" ]
@@ -35,7 +46,7 @@ else
 
 	sudo $cmd_adb kill-server > /dev/null
 	sudo $cmd_adb start-server > /dev/null
-	sudo $cmd_adb forward tcp:2828 tcp:2828 > /dev/null
+	sudo $cmd_adb forward tcp:2828 tcp:2828 > /dev/null 2>/dev/null
 
 	echo "$X"
 	showDevices
